services:
    contelizer.bluemedia_plugin.form.type.gateway_configuration:
        class: Contelizer\SyliusBluemediaPlugin\Form\Type\BluemediaGatewayConfigurationType
        tags:
            - { name: sylius.gateway_configuration_type, type: bluemedia, label: contelizer.bluemedia_plugin.gateway_label }
            - { name: form.type }

    contelizer.bluemedia_plugin.gateway_factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [Contelizer\SyliusBluemediaPlugin\BluemediaGatewayFactory]
        tags:
            - { name: payum.gateway_factory_builder, factory: bluemedia }

    contelizer.bluemedia_plugin.bridge.open_bluemedia:
        class: Contelizer\SyliusBluemediaPlugin\Bridge\OpenBluemediaBridge

    contelizer.bluemedia_plugin.payu_action:
        class: Contelizer\SyliusBluemediaPlugin\Action\PayUAction
        public: true
        arguments: ['@contelizer.bluemedia_plugin.bridge.open_payu', '@payum']
        tags:
            - { name: payum.action, factory: bluemedia, alias: payum.action.set_payu }

    contelizer.bluemedia_plugin.notify_action:
        class: Contelizer\SyliusBluemediaPlugin\Action\NotifyAction
        public: true
        arguments:
            - '@contelizer.bluemedia_plugin.bridge.open_payu'
        tags:
            - { name: payum.action, factory: bluemedia, alias: payum.action.notify }
